LTO_ENABLE = yes
NKRO_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
